### ISSUE TITLE
image不能pull

### ISSUE THREAD

**Issue by BruceChinese** [AliyunContainerService/alibaba-cloud-metrics-adapter#10]
[root@master02 deploy]# docker pull registry.cn-beijing.aliyuncs.com/ringtail/alibaba-cloud-metrics-adapter:v0.1.0-alpha-6431602a-aliyun
Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/ringtail/alibaba-cloud-metrics-adapter:v0.1.0-alpha-6431602a-aliyun not found: manifest unknown: manifest unknown

**Comment by ringtail** [comment]
Fix image to `registry.cn-beijing.aliyuncs.com/acs/alibaba-cloud-metrics-adapter-amd64:v0.1.0-alpha-6431602a-aliyun`
