### ISSUE TITLE
根据用户在线在线数进行触发 ，我应该使用哪个批标

### ISSUE THREAD

**Issue by wangchuang-chn** [AliyunContainerService/alibaba-cloud-metrics-adapter#24]
我kubernetes中准备使用阿里云提供的“阿里云指标容器”， 是需要根据用户连接数来控制HPA， 这边看到4层协议中有三项与用户连接数相关，但是不明白本质上的区别是什么，我应该使用哪一个
slb_l4_active_connection	Active connections	None
slb_l4_max_connection	Maximum number of connections	None
slb_l4_connection_utilization	Maximum connection usage	None

**Comment by ringtail** [comment]
> 我kubernetes中准备使用阿里云提供的“阿里云指标容器”， 是需要根据用户连接数来控制HPA， 这边看到4层协议中有三项与用户连接数相关，但是不明白本质上的区别是什么，我应该使用哪一个
> slb_l4_active_connection Active connections None
> slb_l4_max_connection Maximum number of connections None
> slb_l4_connection_utilization Maximum connection usage None

当你配置的SLB是4层【TCP】，slb_l4_active_connection表示活跃连接数、slb_l4_max_connection表示最大连接数、slb_l4_connection_utilization表示连接数利用率。

业务的时延SLA是多少，另外是否使用了类似Ingress的接入网关
